### ISSUE TITLE
Roadmap: v1.0.0

### ISSUE THREAD

**Issue by matz3** [SAP/ui5-linter#21]
This issue describes the currently foreseen changes for the first stable release of `@ui5/linter`. The list is not exhaustive and may change over time.

## Detection improvements

- [x] Detect usage of deprecated dependencies
  - [x] https://github.com/SAP/ui5-linter/pull/34
  - [x] https://github.com/SAP/ui5-linter/pull/39
  - [x] https://github.com/SAP/ui5-linter/pull/104
- [x] https://github.com/SAP/ui5-linter/pull/23
- [x] https://github.com/SAP/ui5-linter/pull/60
- [x] https://github.com/SAP/ui5-linter/pull/73
- [x] Check JavaScript code within HTML
  - [x] https://github.com/SAP/ui5-linter/pull/48
  - [x] https://github.com/SAP/ui5-linter/pull/316
- [x] https://github.com/SAP/ui5-linter/issues/86
- [x] Detect usage of partially deprecated UI5 APIs (e.g. when only a parameter of a method is deprecated, but not the method itself) (CPOUI5FOUNDATION-788)
  - [x] https://github.com/SAP/ui5-linter/pull/286
  - [x] https://github.com/SAP/ui5-linter/pull/33
- [x] Check TypeScript code (CPOUI5FOUNDATION-845)
  - [x] https://github.com/SAP/ui5-linter/pull/265
  - [x] https://github.com/SAP/ui5-linter/pull/152
- [x] Detect usage of deprecated JSView (CPOUI5FOUNDATION-884)
  - [x] https://github.com/SAP/openui5/commit/0cc1ef7cbe21918337e1bcad5c2b0957c49a5634 
- [x] Detect usage of deprecated JSON/HTML views/fragments (CPOUI5FOUNDATION-883)
  - [x] https://github.com/SAP/ui5-linter/pull/320 

## Features

- [x] https://github.com/SAP/ui5-linter/issues/170 (CPOUI5FOUNDATION-782)
  - [x] https://github.com/SAP/ui5-linter/pull/264

## Optimizations

- [x] Improve performance and reduce memory consumption
  - [x] https://github.com/SAP/ui5-linter/pull/29
  - [x] https://github.com/SAP/ui5-linter/pull/46
  - [x] https://github.com/SAP/ui5-linter/pull/179

**Comment by flovogt** [comment]
UI5 linter [v1.0.0](https://github.com/SAP/ui5-linter/releases/tag/v1.0.0) is released and all mentioned features are implemented.
