### ISSUE TITLE
Roadmap: Next

### ISSUE THREAD

**Issue by flovogt** [SAP/ui5-linter#323]
# Roadmap: Next

## Detection improvements

- [ ] Detect usage of private/restricted UI5 APIs (in discussion)
- [ ] Check for Control best practices (CPOUI5FOUNDATION-858)

## Features

- [ ] Allow configuration of UI5 version (CPOUI5FOUNDATION-856)
  -  Currently, the latest LTS version 1.120 is used
- [ ] Provide a Node.js API (CPOUI5FOUNDATION-885)
